### PR TITLE
Last changes for today

### PR DESCRIPTION
**Pull request by deavmi**
Just some more changes.

### CODE REVIEW

**Comment by deavmi** [comment]
Let me see.

**Comment by cdpxe** [comment]
Hi @deavmi ,
do you have the necessary access to merge your commit? I have no objection here as this would enhance the documentation.
Kind regards,
Steffen

**Comment by deavmi** [comment]
I have access to your repo yes.

**Comment by deavmi** [comment]
This was an old PR from my personal repo.

**Comment by cdpxe** [comment]
Okay, then you can close the pull request.
thanks, Steffen

**Pull request closed without merging**
